// 纯运输页面文案：[中文, English, Bahasa Indonesia]
const copy = {
  // 分页签
  tabOrders: ["需求单", "Orders", "Pesanan"],
  tabDispatch: ["调度", "Dispatch", "Penugasan"],
  tabTrips: ["趟次", "Trips", "Trip"],
  tabExceptions: ["异常", "Exceptions", "Pengecualian"],
  tabTariffs: ["报价", "Tariffs", "Tarif"],
  tabCharges: ["费用", "Charges", "Biaya"],

  // 通用
  search: ["搜索", "Search", "Cari"],
  refresh: ["刷新", "Refresh", "Muat ulang"],
  all: ["全部", "All", "Semua"],
  customer: ["客户", "Customer", "Pelanggan"],
  requestNo: ["客户订单号", "Customer ref.", "No. pesanan pelanggan"],
  orderCode: ["需求单号", "Order no.", "No. pesanan"],
  origin: ["发货地", "Origin", "Asal"],
  destination: ["收货地", "Destination", "Tujuan"],
  region: ["区域", "Region", "Wilayah"],
  vin: ["VIN", "VIN", "VIN"],
  vehicle: ["车辆", "Vehicle", "Kendaraan"],
  config: ["配置", "Type", "Tipe"],
  model: ["型号", "Model", "Model"],
  color: ["颜色", "Color", "Warna"],
  towType: ["拖车类型", "Armada", "Armada"],
  carrier: ["物流商", "Vendor", "Vendor"],
  driver: ["司机", "Driver", "Sopir"],
  trailer: ["拖车", "Trailer", "Trailer"],
  status: ["状态", "Status", "Status"],
  quantity: ["数量", "Quantity", "Jumlah"],
  pickupDate: ["计划提货", "Pickup date", "Tgl. ambil"],
  deliveryDate: ["计划到达", "Delivery date", "Tgl. tiba"],
  remark: ["备注", "Remark", "Catatan"],
  reason: ["原因", "Reason", "Alasan"],
  reasonRequired: ["请填写原因", "Enter a reason", "Isi alasan"],
  cancel: ["取消", "Cancel", "Batal"],
  confirm: ["确认", "Confirm", "Konfirmasi"],
  save: ["保存", "Save", "Simpan"],
  edit: ["编辑", "Edit", "Ubah"],
  delete: ["删除", "Delete", "Hapus"],
  saved: ["已保存", "Saved", "Tersimpan"],
  done: ["已完成", "Done", "Selesai"],
  noVin: ["待补", "Pending", "Menunggu"],
  events: ["操作记录", "Activity", "Riwayat"],
  operator: ["操作人", "By", "Oleh"],
  time: ["时间", "Time", "Waktu"],
  lines: ["车辆明细", "Vehicles", "Kendaraan"],
  selected: ["已选 {n} 台", "{n} selected", "{n} dipilih"],
  loadFailed: ["加载失败，请刷新重试", "Load failed. Refresh to retry", "Gagal memuat. Coba lagi"],

  // 需求单
  newOrder: ["新建需求单", "New order", "Pesanan baru"],
  importExcel: ["Excel 导入", "Import Excel", "Impor Excel"],
  downloadTemplate: ["下载模板", "Download template", "Unduh templat"],
  lineCount: ["台数", "Cars", "Unit"],
  progress: ["进度", "Progress", "Progres"],
  missingVin: ["{n} 台待补 VIN", "{n} VINs pending", "{n} VIN belum ada"],
  unallocated: ["{n} 台待分配", "{n} to allocate", "{n} belum dialokasi"],
  addRow: ["添加一行", "Add row", "Tambah baris"],
  vinOrQty: ["填 VIN 为一台；不填 VIN 时按数量生成空明细", "A VIN is one car; without a VIN, the quantity creates empty lines", "VIN = satu unit; tanpa VIN, jumlah membuat baris kosong"],
  chooseCustomerFirst: ["先选择客户", "Choose a customer first", "Pilih pelanggan dulu"],
  supplementVin: ["补 VIN", "Add VINs", "Isi VIN"],
  supplementHint: ["为空 VIN 的明细填入车架号，可整列粘贴", "Fill VINs for empty lines. You can paste a whole column", "Isi VIN untuk baris kosong. Bisa tempel satu kolom"],
  pasteVins: ["粘贴 VIN（按顺序填入）", "Paste VINs (filled in order)", "Tempel VIN (diisi berurutan)"],
  cancelOrder: ["取消需求单", "Cancel order", "Batalkan pesanan"],
  cancelOrderHint: ["只会取消还没提货的车辆，已提货的车继续运输", "Only cars not yet picked up are cancelled", "Hanya unit yang belum diambil yang dibatalkan"],
  cancelLines: ["取消所选车辆", "Cancel selected", "Batalkan pilihan"],
  documents: ["回单", "POD", "POD"],
  importPreview: ["预览", "Preview", "Pratinjau"],
  importConfirm: ["确认导入", "Import", "Impor"],
  importErrors: ["有 {n} 行需要修改，修正 Excel 后重新上传", "{n} rows need fixing. Correct the file and upload again", "{n} baris perlu diperbaiki. Perbaiki file lalu unggah lagi"],
  importReady: ["校验通过：{orders} 张需求单，{lines} 台车", "Ready: {orders} orders, {lines} cars", "Siap: {orders} pesanan, {lines} unit"],
  importDone: ["已导入 {n} 张需求单", "Imported {n} orders", "{n} pesanan diimpor"],
  row: ["行", "Row", "Baris"],
  withVin: ["有 VIN", "With VIN", "Ber-VIN"],
  preAllocated: ["已指定物流商", "Vendor set", "Vendor ditetapkan"],
  importHint: ["一行一台车；没有 VIN 时填 Quantity。Origin、Dealer 填客户地址簿编码，Vendor 填物流商简称。", "One row per car; use Quantity when there is no VIN. Origin and Dealer use address-book codes; Vendor uses the carrier short name.", "Satu baris satu unit; isi Quantity jika tanpa VIN. Origin dan Dealer memakai kode buku alamat; Vendor memakai nama singkat."],

  // 调度
  allocate: ["分配物流商", "Assign vendor", "Tetapkan vendor"],
  createTrip: ["派车", "Dispatch", "Tugaskan"],
  addToTrip: ["加到趟次", "Add to trip", "Tambah ke trip"],
  capacityLeft: ["载量 {cap} 台", "Capacity {cap}", "Kapasitas {cap}"],
  overCapacity: ["超出载量：该拖车最多 {cap} 台", "Over capacity: this trailer takes {cap}", "Melebihi kapasitas: maks {cap} unit"],
  sameCarrier: ["所选车辆必须属于同一物流商、同一拖车类型", "Selected cars must share one vendor and armada", "Unit terpilih harus satu vendor dan armada"],
  poolHint: ["先按台分配物流商和拖车类型，再选车派车；一趟可以跨发货地、跨门店、跨客户", "Assign vendor and armada per car, then dispatch. A trip can span origins, stores and customers", "Tetapkan vendor dan armada per unit, lalu tugaskan. Satu trip bisa lintas asal, dealer, dan pelanggan"],
  openTrip: ["未发车趟次", "Open trip", "Trip terbuka"],

  // 趟次
  tripCode: ["趟次号", "Trip no.", "No. trip"],
  loaded: ["已装", "Loaded", "Dimuat"],
  delivered: ["已签收", "Delivered", "Diterima"],
  legs: ["运输段", "Legs", "Rute"],
  legHint: ["每个“发货地→收货地”组合一张 POD", "One POD per origin → destination pair", "Satu POD per pasangan asal → tujuan"],
  uploadPod: ["上传 POD", "Upload POD", "Unggah POD"],
  podInvalid: ["请选择 20 MB 以内的 PDF 或 JPG", "Choose a PDF or JPG up to 20 MB", "Pilih PDF atau JPG maks 20 MB"],
  uploaded: ["已上传", "Uploaded", "Terunggah"],
  scanPickup: ["提货录入", "Record pickup", "Catat ambil"],
  scanSign: ["签收录入", "Record delivery", "Catat terima"],
  vinPlaceholder: ["扫描或输入 VIN 后回车", "Scan or type a VIN, then Enter", "Pindai atau ketik VIN, lalu Enter"],
  chooseLine: ["这台车送哪个门店？", "Which store is this car for?", "Unit ini untuk dealer mana?"],
  depart: ["发车", "Depart", "Berangkat"],
  departConfirm: ["未装的 {n} 台会退回待派车。确认发车？", "{n} cars not loaded go back to the pool. Depart?", "{n} unit yang belum dimuat kembali ke antrean. Berangkat?"],
  departed: ["已发车", "Departed", "Berangkat"],
  cancelTrip: ["取消趟次", "Cancel trip", "Batalkan trip"],
  removeFromTrip: ["移出趟次", "Remove from trip", "Keluarkan dari trip"],
  recordException: ["登记货损/拒收", "Record damage / refusal", "Catat kerusakan / penolakan"],
  closeLine: ["关闭（拒收/退回）", "Close (refused / returned)", "Tutup (ditolak / kembali)"],
  picked: ["{vin} 已提货", "{vin} picked up", "{vin} diambil"],
  signedOk: ["{vin} 已签收", "{vin} delivered", "{vin} diterima"],
  unplannedScanned: ["{vin} 不在计划内，已提交内部处理", "{vin} is not planned; sent for review", "{vin} di luar rencana; dikirim untuk ditinjau"],

  // 异常
  exceptionType: ["类型", "Type", "Jenis"],
  UNPLANNED_VIN: ["计划外车辆", "Unplanned VIN", "VIN di luar rencana"],
  DAMAGE: ["货损", "Damage", "Kerusakan"],
  REFUSED: ["拒收", "Refused", "Ditolak"],
  OTHER: ["其他", "Other", "Lainnya"],
  OPEN: ["待处理", "Open", "Terbuka"],
  RESOLVED: ["已处理", "Resolved", "Selesai"],
  RECORDED: ["已记录", "Recorded", "Tercatat"],
  resolve: ["处理", "Resolve", "Tangani"],
  decisionBIND: ["顶替/填入本趟一台", "Use for a car on this trip", "Pakai untuk unit di trip ini"],
  decisionADD: ["作为追加车辆", "Add as extra car", "Tambah sebagai unit ekstra"],
  decisionREJECT: ["驳回（车辆不运）", "Reject (not transported)", "Tolak (tidak diangkut)"],
  targetLine: ["本趟次的明细", "Line on this trip", "Baris di trip ini"],
  targetOrder: ["加到哪张需求单", "Add to order", "Tambah ke pesanan"],
  note: ["说明", "Note", "Keterangan"],

  // 报价
  side: ["方向", "Side", "Sisi"],
  RECEIVABLE: ["应收", "Receivable", "Piutang"],
  PAYABLE: ["应付", "Payable", "Hutang"],
  newTariff: ["新增报价", "New tariff", "Tarif baru"],
  price: ["单价（每台）", "Price per car", "Harga per unit"],
  validFrom: ["开始日期", "Valid from", "Berlaku dari"],
  validTo: ["结束日期", "Valid to", "Berlaku sampai"],
  openEnded: ["长期", "Open-ended", "Tanpa batas"],
  destinationStore: ["收货门店", "Store", "Dealer"],
  storeOrRegion: ["门店或区域（二选一）", "Store or region (one of)", "Dealer atau wilayah (salah satu)"],
  tariffHint: ["应收按“客户+发货地+门店+拖车类型”；应付按“客户+物流商+发货地+门店或区域+拖车类型”。币种为机构默认币种。", "Receivable: customer + origin + store + armada. Payable: customer + vendor + origin + store or region + armada. Currency follows the organization.", "Piutang: pelanggan + asal + dealer + armada. Hutang: pelanggan + vendor + asal + dealer atau wilayah + armada. Mata uang ikut organisasi."],
  deleteConfirm: ["确认删除？已生成的费用不受影响", "Delete? Existing charges keep their amounts", "Hapus? Biaya yang ada tidak berubah"],

  // 费用
  amount: ["金额", "Amount", "Jumlah"],
  pricing: ["计价", "Pricing", "Harga"],
  TARIFF: ["报价", "Tariff", "Tarif"],
  UNPRICED: ["待定价", "Unpriced", "Belum ada harga"],
  MANUAL: ["手工调整", "Adjusted", "Disesuaikan"],
  PENDING: ["待确认", "Pending", "Menunggu"],
  CONFIRMED: ["已确认", "Confirmed", "Dikonfirmasi"],
  serviceDate: ["签收日期", "Delivered on", "Tgl. diterima"],
  adjust: ["调整金额", "Adjust", "Sesuaikan"],
  confirmSelected: ["确认所选", "Confirm selected", "Konfirmasi pilihan"],
  recalculate: ["按报价重算", "Recalculate", "Hitung ulang"],
  recalculateHint: ["重算范围内未确认的费用；默认保留手工调整过的金额", "Recalculates unconfirmed charges in range; manual amounts are kept by default", "Menghitung ulang biaya yang belum dikonfirmasi; nilai manual tetap"],
  includeManual: ["同时覆盖手工调整", "Also overwrite manual amounts", "Timpa juga nilai manual"],
  recalculated: ["已检查 {checked} 条，更新 {updated} 条", "Checked {checked}, updated {updated}", "Diperiksa {checked}, diperbarui {updated}"],
  unpricedCount: ["{n} 条待定价", "{n} unpriced", "{n} belum ada harga"],

  // 状态
  L_UNALLOCATED: ["待分配", "To assign", "Belum dialokasi"],
  L_ALLOCATED: ["待派车", "To dispatch", "Menunggu trip"],
  L_DISPATCHED: ["待提货", "To pick up", "Menunggu ambil"],
  L_PICKED_UP: ["已装车", "Loaded", "Dimuat"],
  L_IN_TRANSIT: ["运输中", "In transit", "Dalam perjalanan"],
  L_DELIVERED: ["已签收", "Delivered", "Diterima"],
  L_CLOSED: ["已关闭", "Closed", "Ditutup"],
  L_CANCELLED: ["已取消", "Cancelled", "Dibatalkan"],
  T_PLANNED: ["待提货", "Planned", "Direncanakan"],
  T_LOADING: ["装车中", "Loading", "Memuat"],
  T_IN_TRANSIT: ["运输中", "In transit", "Dalam perjalanan"],
  T_COMPLETED: ["已完成", "Completed", "Selesai"],
  T_CANCELLED: ["已取消", "Cancelled", "Dibatalkan"],
  O_OPEN: ["进行中", "Open", "Berjalan"],
  O_COMPLETED: ["已完成", "Completed", "Selesai"],
  O_CANCELLED: ["已取消", "Cancelled", "Dibatalkan"],

  // 操作记录
  ORDER_CREATED: ["创建需求单", "Order created", "Pesanan dibuat"],
  ORDER_CANCELLED: ["取消需求单", "Order cancelled", "Pesanan dibatalkan"],
  LINE_CREATED: ["新增车辆", "Car added", "Unit ditambahkan"],
  LINE_UPDATED: ["修改车辆", "Car updated", "Unit diubah"],
  VIN_SUPPLEMENTED: ["补 VIN", "VIN added", "VIN diisi"],
  LINE_ALLOCATED: ["分配物流商", "Vendor assigned", "Vendor ditetapkan"],
  LINE_DISPATCHED: ["派车", "Dispatched", "Ditugaskan"],
  LINE_PICKED_UP: ["提货", "Picked up", "Diambil"],
  LINE_NOT_LOADED: ["发车时未装，退回待派车", "Not loaded; back to pool", "Tidak dimuat; kembali ke antrean"],
  LINE_REMOVED_FROM_TRIP: ["移出趟次", "Removed from trip", "Dikeluarkan dari trip"],
  LINE_DELIVERED: ["签收", "Delivered", "Diterima"],
  LINE_CLOSED: ["关闭", "Closed", "Ditutup"],
  LINE_CANCELLED: ["取消车辆", "Car cancelled", "Unit dibatalkan"],
  LINE_ADDED_FROM_SCAN: ["追加车辆", "Extra car added", "Unit ekstra ditambahkan"],
  VIN_REPLACED: ["VIN 被顶替", "VIN replaced", "VIN diganti"],
  UNPLANNED_VIN_SCANNED: ["扫到计划外车辆", "Unplanned VIN scanned", "VIN di luar rencana dipindai"],
  UNPLANNED_VIN_RESOLVED: ["处理计划外车辆", "Unplanned VIN resolved", "VIN di luar rencana ditangani"],
  TRIP_CREATED: ["创建趟次", "Trip created", "Trip dibuat"],
  TRIP_DEPARTED: ["发车", "Departed", "Berangkat"],
  TRIP_COMPLETED: ["趟次完成", "Trip completed", "Trip selesai"],
  TRIP_CANCELLED: ["取消趟次", "Trip cancelled", "Trip dibatalkan"],
  POD_UPLOADED: ["上传 POD", "POD uploaded", "POD diunggah"],
  EXCEPTION_DAMAGE: ["登记货损", "Damage recorded", "Kerusakan dicatat"],
  EXCEPTION_REFUSED: ["登记拒收", "Refusal recorded", "Penolakan dicatat"],
  EXCEPTION_OTHER: ["登记异常", "Issue recorded", "Masalah dicatat"],
  CHARGE_ADJUSTED: ["调整费用", "Charge adjusted", "Biaya disesuaikan"],
  CHARGE_RECALCULATED: ["重算费用", "Charge recalculated", "Biaya dihitung ulang"],
} as const;

export type TransportCopyKey = keyof typeof copy;

export function transportText(locale: string) {
  const index = locale === "zh" ? 0 : locale === "id" ? 2 : 1;
  return (key: string, vars?: Record<string, string | number>): string => {
    let text: string = copy[key as TransportCopyKey]?.[index] ?? key;
    if (vars)
      for (const [k, v] of Object.entries(vars)) text = text.replace(`{${k}}`, String(v));
    return text;
  };
}

export type TransportT = ReturnType<typeof transportText>;
